apiVersion: v1
kind: List
items:
{%- for item in kind.ConfigMap %}
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: {{ item.name }}
{%- if kind.Namespace.global_env == "production" %}
    namespace: {{ kind.Namespace.project_name }}
{%- else %}
    namespace: {{ kind.Namespace.project_name }}-{{ kind.Namespace.global_env }}
{%- endif %}
  data:
    {{ item.file_name }}: |
      {{ conf(item.name)|safe|indent(6) }}
{%- endfor -%}
