apiVersion: v1
kind: Namespace
metadata:
{%- if kind.Namespace.global_env == "production" %}
  name: {{ kind.Namespace.project_name }}
{%- else %}
  name: {{ kind.Namespace.project_name }}-{{ kind.Namespace.global_env }}
{%- endif %}
