apiVersion: v1
kind: List
items:
{%- for item in kind.Secret %}
- apiVersion: v1
  kind: Secret
  metadata:
{%- if item == "dockerconfigjson" %}
    name: dockerconfigjson
{%- else %}
    name: {{ kind.Namespace.part }}-{{ item }}
{% endif %}
{%- if kind.Namespace.global_env == "production" %}
    namespace: {{ kind.Namespace.project_name }}
{%- else %}
    namespace: {{ kind.Namespace.project_name }}-{{ kind.Namespace.global_env }}
{%- endif %}
  type: kubernetes.io/{{ item }}
  data:
    {{ conf(item) | indent(4) }}
{%- endfor %}
